pramen/core/src/main/resources/reference.conf
pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala

They are replaces with '_' in column names on ingestion.

Add support for configurable column special characters.

---

pramen-py/src/pramen_py/app/cli.py
pramen-py/tests/test_app/test_cli.py

#66 Made that list-configuration-options command was independent 2

---

pramen/core/src/main/scala/za/co/absa/pramen/core/sink/CsvConversionParams.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sink/LocalCsvSink.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/sink/CsvConversionParamsFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/sink/LocalCsvSinkSuite.scala

#72 Allow creation of empty CSV files for the local CSV sink.

---

.github/workflows/scala.yml
README.md
pramen/api/src/main/scala/za/co/absa/pramen/api/ExternalChannel.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/Sink.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/Source.scala
pramen/core/pom.xml
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/LocalSparkSource.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/ParquetSource.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/SparkSource.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/LocalFsUtils.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/traverser/FileStatus.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/traverser/FsTraverser.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/traverser/FsTraverserLocal.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/base/SparkTestBase.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/job/SourceSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/LocalSparkSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperNullSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/LocalFsUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/traverser/FsTraverserLocalSuite.scala
pramen/pom.xml

#73 Implement local spark source

---

.gitignore
README.md
pramen/build.sbt
pramen/core/src/main/scala/za/co/absa/pramen/core/source/LocalSparkSource.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/lock/TokenLockJdbcSuite.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusConfig.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/utils/MainRunner.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/mocks/AppMainMock.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/mocks/AppMainSilentMock.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusConfigSuite.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusSinkSuite.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/utils/MainRunnerSuite.scala
pramen/project/build.properties

Ussage:
```
pramen.sources = [
{
...
enceladus.run.main.class = "za.co.absa.enceladus.standardization_conformance.StandardizationAndConformanceJob"
enceladus.command.line.template = "--dataset-name @datasetName --dataset-version @datasetVersion --report-date @infoDate --menas-auth-keytab menas.keytab --raw-format @rawFormat"
}
]
```
```
pramen.operarions = [
{
...
tables = [
{
...
dataset.name = "my_dataset"
dataset.version = "22"
}
] 
}
]
```
Closes #75

#75 implement DCE launcher from Pramen

---

pramen/core/src/test/scala/za/co/absa/pramen/core/fixtures/TempDirFixture.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PipelineDefSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/sink/LocalCsvSinkSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/FsUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JsonUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/LocalFsUtilsSuite.scala

Fixed issues related to differences between Windows and Unix filesystem paths. Unit tests can now be run unit on Windows without failures.

Fixed issues related to differences between Windows and Unix filesystem paths

---

pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/RuntimeConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/RuntimeConfigSuite.scala
pramen/runner/src/main/scala/za/co/absa/pramen/runner/cmd/CmdLineConfig.scala
pramen/runner/src/test/scala/za/co/absa/pramen/tests/CmdLineConfigSuite.scala

Added an option to specify number of parallel tasks by a command line parameter.

#152 Add a command-line option to specify number of parallel tasks.

---

pramen/examples/enceladus_single_config/daily_mainframe_ingestion.conf

#160 Add mainframe ingestion example configuration.

---

pramen/extras/src/main/scala/za/co/absa/pramen/extras/infofile/InfoFileGeneration.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationConfig.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationSink.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/builtin/infofile/InfoFileGenerationSuite.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/StandardizationConfigSuite.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/StandardizationSinkSuite.scala

This is the initial implementation that is not integrated with Menas yet, and does not expose Hive yet. But this new sink allows quickly publishing data that is already strongly typed (JDBC, Cobol, ...) directly to the publish layer.

#162 Standardization sink

---

pramen/runner/src/main/scala/za/co/absa/pramen/runner/RunnerCommons.scala
pramen/runner/src/test/scala/za/co/absa/pramen/runner/RunnerCommonsSuite.scala

The Typesafe library seems ignoring the fact that the file does not exist and complains that some configuration keys are missing. This PR suppose to add more smart behavior to it.

#167 Make checking of the workflow configuration file existence smarter.

---

README.md
pramen/api/src/main/scala/za/co/absa/pramen/api/Source.scala

It should make performance optimization possible in the future.

#184 Add the method to the Source trait 

---

pramen/version.sbt

The release introduces the change to the Source trait to allow source validations.

Release Pramen v1.4.0

---

pramen/api/src/main/scala/za/co/absa/pramen/api/TaskNotification.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/message/MessageBuilderHtml.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/jobrunner/ConcurrentJobRunnerImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/OrchestratorImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskResult.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala
pramen/core/src/test/resources/test/notify/expectedMessage.dat
pramen/core/src/test/resources/test/notify/test_pipeline_email_body_complex.txt
pramen/core/src/test/scala/za/co/absa/pramen/core/TaskNotificationFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TaskResultFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/runner/ConcurrentJobRunnerSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/SourceValidationSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/TaskCompletedSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/jobrunner/TaskRunnerMultithreadedSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/task/TaskRunnerBaseSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationSink.scala

- #197 Include Spark application ID to the notification so it is easier to track job logs
- #198 Include cause chain of exceptions to get more insight in case of failures
Closes #197, #198

Improve email notifications 

---

pramen/version.sbt

* #196 Make Hive enablement an explicit parameter. by @yruslan in https://github.com/AbsaOSS/pramen/pull/199
* #197 Add Spark application Id to email notifications email notifications  by @yruslan in https://github.com/AbsaOSS/pramen/pull/200
* #198 Improve exceptions rendering in notifications by @yruslan in https://github.com/AbsaOSS/pramen/pull/200

Release Pramen v1.4.1

---

pramen/version.sbt

* #203 Add spark catalog support as one of Hive integration options by @yruslan in https://github.com/AbsaOSS/pramen/pull/206
* #208 Make AppRunner recreate AppContext on every run by @jirifilip in https://github.com/AbsaOSS/pramen/pull/208
* #209 Improve EnceladusSink to support Hive external table creation by @yruslan in https://github.com/AbsaOSS/pramen/pull/209
* #210 Improve StandardizationSink to support Delta as publish format by @yruslan in https://github.com/AbsaOSS/pramen/pull/210
* #205 Allows spreading object array elements among multiple config files. by @yruslan in https://github.com/AbsaOSS/pramen/pull/211

Release Pramen v1.4.2

---

pramen/version.sbt

* #225 Log executor nodes in https://github.com/AbsaOSS/pramen/pull/226
* #227 Add support for verbose log suppression for Spark 3.3+. in https://github.com/AbsaOSS/pramen/pull/228
* #229 Allow passing transformer configuration to the constructor in https://github.com/AbsaOSS/pramen/pull/231
* #232 Add the ability to specify alternative path to Hive tables if it differs from the table path in https://github.com/AbsaOSS/pramen/pull/233

Release Pramen v1.5.1

---

pramen/version.sbt

* #221 Add support for transient metastore tables in https://github.com/AbsaOSS/pramen/pull/243
**Full Changelog**: https://github.com/AbsaOSS/pramen/compare/v1.5.2...v1.6.0

Release Pramen v1.6.0

---

pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala
pramen/core/src/test/resources/test/notify/test_pipeline_email_body_complex.txt
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala

...and remove extra backquotes from the full table name.

#255 Change 'Hive' notification column to 'Catalog' 

---

pramen/api/src/main/scala/za/co/absa/pramen/api/MetaTableRunInfo.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/Source.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/Transformer.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransformationJob.scala

#261 Add postprocessing methods to transformers and sources.

---

pramen/api/pom.xml
pramen/build_all.sh
pramen/core/pom.xml
pramen/deploy_aqua.sh
pramen/deploy_binks.sh
pramen/deploy_chew.sh
pramen/deploy_inaas.sh
pramen/extras/pom.xml
pramen/pom.xml
pramen/runner/pom.xml
pramen/version.sbt

* #252 Add support for keeping arbitrary metadata for metastore table pertitions in https://github.com/AbsaOSS/pramen/pull/259
* #258 Make Spark Application name configurable in https://github.com/AbsaOSS/pramen/pull/260
* #261 Add postprocessing methods to transformers and sources in https://github.com/AbsaOSS/pramen/pull/262

Release Pramen v1.6.2

---

pramen/version.sbt

* #263 Extend custom notification entries with lists, attached files and custom HTML blocks in https://github.com/AbsaOSS/pramen/pull/265
* #266 Allow copying of files between file systems in https://github.com/AbsaOSS/pramen/pull/267
* #268 Add support for Varchar type when exposing tables in Hive in https://github.com/AbsaOSS/pramen/pull/269
* #270 Add Spark 3.5.0 support, update Scala and Spark dependencies to the latest patches in https://github.com/AbsaOSS/pramen/pull/271

Release v1.6.3

---

pramen/version.sbt

* #263 Add ability to specify custom startup and shutdown hooks in https://github.com/AbsaOSS/pramen/pull/274
* #275 Implement custom notification signatures for email notifications in https://github.com/AbsaOSS/pramen/pull/277
* #276 Add maximumLength field metadata for JDBC 'varchar' fields in https://github.com/AbsaOSS/pramen/pull/278

Release v1.6.4

---

pramen/build.sbt
pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/HookConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/exceptions/FatalErrorWrapper.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/jobrunner/ConcurrentJobRunnerImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineState.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateSnapshot.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/HookConfigSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/RunnableSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/state/PipelineStateSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/state/ShutdownHookFailureMock.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/state/ShutdownHookSuccessMock.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/state/PipelineStateSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/AppRunnerSuite.scala

#287 Send email notifications if instantiating of hooks failed.

---

.github/workflows/jacoco.yml
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderSpark.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/SparkSource.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/reader/TableReaderSparkFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/LocalSparkSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/SparkSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderSparkSuite.scala

Make 'format' parameter of SparkSource optional.

---

README.md
pramen/core/src/main/resources/reference.conf
pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/GeneralConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/DependencyResolverImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/Orchestrator.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/OrchestratorImpl.scala
pramen/core/src/test/resources/log4j.properties
pramen/core/src/test/resources/log4j2.properties
pramen/core/src/test/resources/test/config/integration_multi_table_transformers.conf
pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/GeneralConfigSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/integration/MultiJobTransformersSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/GeneratingTransformer.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/orchestrator/DependencyResolverSuite.scala

#294 Allow multiple transformers output to the same table

---

README.md
pramen-py/pyproject.toml
pramen/publish.sbt
pramen/version.sbt

* #279 When 'trackDays=0', Pramen never checks source data record count if the table is already loaded for the day in https://github.com/AbsaOSS/pramen/pull/280
* #283 Add support for using Spark JDBC connectors for SELECT SQL queries in https://github.com/AbsaOSS/pramen/pull/300
* #291 Combine 'core' and 'runner' modules into 'core' in https://github.com/AbsaOSS/pramen/pull/297
* #292 Fix the last expected info date calculation in https://github.com/AbsaOSS/pramen/pull/293
* #294 Allow multiple transformers output to the same table in https://github.com/AbsaOSS/pramen/pull/296
* #295 Make 'format' parameter of SparkSource optional in https://github.com/AbsaOSS/pramen/pull/295
* #298 Do not include Delta Lake classes in the runner bundle by default in …

Release Pramen v1.7.0

---

pramen/version.sbt

* #286 Add options to set informtation start date relative to the current date in https://github.com/AbsaOSS/pramen/pull/313
* #306 Report a job as New when it never ran, but a rerun is requested in https://github.com/AbsaOSS/pramen/pull/308
* #312 Fix the requirement of 'information.date.format.sql' to be present for the JDBC source. by @yruslan in https://github.com/AbsaOSS/pramen/pull/315

Release Pramen v1.7.1

---

pramen/api/src/main/scala/za/co/absa/pramen/api/ExternalChannelFactoryV2.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/ExternalChannelFactoryReflect.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/Sendable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/LocalSparkSource.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/ExternalChannelFactorySuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/ExternalChannelV2Mock.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/LocalSparkSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/RawFileSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/SparkSourceSuite.scala

#319 Add a trait (ExternalChannelFactoryV2) for creating custom sources or sinks with access to teh workflow configuration

---

pramen/version.sbt

* #314 Make `information.date.sql.format`obsolete in https://github.com/AbsaOSS/pramen/pull/318
* #317 Escape column names in SQL queries when it contains non-alphanumeric characters or a possible keyword in https://github.com/AbsaOSS/pramen/pull/320
* #319 Add a trait (ExternalChannelFactoryV2) for creating custom sources or sinks with access to teh workflow configuration in https://github.com/AbsaOSS/pramen/pull/321

Release Pramen v1.7.2

---

pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineStatus.scala
pramen/core/src/test/resources/test/notify/test_pipeline_email_body_complex.txt
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala

#327 Add status indicators to the email subject, extend statuses with new 'Warning' status

---

README.md
pramen-py/pyproject.toml
pramen/version.sbt

* #327 Add status indicators to the email subject, extend statuses with new 'Warning' status in https://github.com/AbsaOSS/pramen/pull/328
* #325 Add quoting policy that help validate and quote identifiers that are passed to SQL queries in https://github.com/AbsaOSS/pramen/pull/329
* #324 Make string to date conversion for MS SQL Server queries graceful in https://github.com/AbsaOSS/pramen/pull/331

Release Pramen v1.7.3

---

README.md
pramen/version.sbt

* #311 Add the ability to run multiple workflows in a single Spark Session in https://github.com/AbsaOSS/pramen/pull/334
* Fix table header gradient CSS style for some of email clients  in https://github.com/AbsaOSS/pramen/pull/334

Release Pramen v1.7.4

---

pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGenerator.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGeneratorBase.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDb2.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHsqlDb.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorOracle.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorSas.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/SqlGeneratorDummy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala

#351 Add a method to SQL generators interface to return an alias expression.

---

README.md
pramen/examples/enceladus_single_config/daily_ingestion.conf
pramen/examples/enceladus_single_config/daily_mainframe_ingestion.conf
pramen/examples/enceladus_single_config/weekly_ingestion.conf
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/HttpDeleteWithBody.scala
pramen/project/Dependencies.scala
pramen/project/Versions.scala

This PR adds the ability to call an API that cleans deleted temporary file versions on versioned buckets.

#361 Add the ability of EnceladusSink to send a REST request to delete temporary version files on S3.

---

pramen/api/src/main/scala/za/co/absa/pramen/api/Pramen.scala
pramen/api/src/test/scala/za/co/absa/pramen/api/mocks/DummyPramen.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/PramenImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/PramenImplSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineStateSnapshotFactory.scala

#403 Add the ability to get currently completed tasks from anywhere from user's code.

---

README.md
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveDefaultConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/MetaTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SourceTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransferTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sink/SparkSink.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sink/SparkSinkFormat.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/AlgorithmUtils.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelper.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelperSql.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/HiveConfigSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/sink/SparkSinkFormatSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/AlgorithmUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSqlSuite.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationSink.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/StandardizationSinkSuite.scala

#410 Improve Spark sink to allow output to table and connection data targets 

---

.github/CODEOWNERS

I am no longer able to efficiently track changes in this repo. I'll be still happy to help in the python part of the project. Feel free to reach me out (check my gh profile for a contact details)

Remove @zhukovgreen from code owners

---

pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGeneratorBase.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala

#427 Add support for double quoted identifiers in MS SQL dialect.

---

pramen-py/pyproject.toml
pramen/version.sbt

* #430 Add configurable maximum execution time warning in https://github.com/AbsaOSS/pramen/pull/431
* #427 Add support for double quoted identifiers in MS SQL dialect in https://github.com/AbsaOSS/pramen/pull/432
* #427 Fix edge cases of MS SQL dialect double quote escaping support in https://github.com/AbsaOSS/pramen/pull/433
* #435 Fix running tests involving embedded MongoDb on incompatible platforms in https://github.com/AbsaOSS/pramen/pull/436
* #426 Fix addPipelineNotificationFailure() not being called in https://github.com/AbsaOSS/pramen/pull/437
* #438 Optimize hive table existence query in https://github.com/AbsaOSS/pramen/pull/439

Release Pramen v1.9.1

---

README.md
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/JdbcUrlSelectorImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/JdbcConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala
pramen/project/Versions.scala

#440 Fix PostgreSQL loading full query results into memory

---

README.md
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveDefaultConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/JdbcConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ConfigUtils.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelper.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/QueryExecutorJdbc.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/HiveConfigSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/QueryExecutorJdbcSuite.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationConfig.scala
pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationSink.scala

#443 Move 'optimize.exist.query' to Hive options instead of JDBC, and make it 'true' by default.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcSparkUtilsSuite.scala

#448 Add support for metadata of UUID column data type in PostgreSQL

---

README.md
pramen/core/src/main/resources/reference.conf
pramen/core/src/main/scala/za/co/absa/pramen/core/RunnerCommons.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveDefaultConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/MetaTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationDef.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransferTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/JdbcUrlSelectorImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/PipelineSparkSessionBuilder.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ConfigUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/MetaTableFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TransferTableFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransferTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/PipelineSparkSessionBuilderSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/ConfigUtilsSuite.scala
pramen/examples/combined_example.sh

#447 Add `spark.conf` option configurable for metastore tables

---

pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/MetaTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistence.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceDelta.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceParquet.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceRaw.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransferTable.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/DataFormatSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceParquetSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceRawSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/MetaTableFactory.scala

#434 Add experimental save mode option for metastore tables

---

pramen/api/src/main/scala/za/co/absa/pramen/api/Pramen.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/status/PipelineStateSnapshot.scala
pramen/api/src/test/scala/za/co/absa/pramen/api/mocks/DummyPramen.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/PramenImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotification.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilder.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationDirector.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineState.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineNotificationFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineStateSnapshotFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/PipelineNotificationBuilderSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/state/PipelineStateSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationDirectorSuite.scala

#463 Add pipeline-wide warning flag so that transformers can change the state of the pipeline.

---

pramen/api/src/main/scala/za/co/absa/pramen/api/PipelineInfo.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/JournalHadoop.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/JournalJdbc.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/JournalTask.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/JournalTasks.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/TaskCompleted.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/TaskCompletedCsv.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PipelineDef.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/rdb/PramenDb.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineInfoFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TaskCompletedFactory.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/TaskCompletedSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/TestCases.scala
pramen/extras/src/test/scala/za/co/absa/pramen/extras/notification/EcsPipelineNotificationTargetSuite.scala

#451 Add spark_application_id to journal

---

pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala

#499 Escape HTML in error messages.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/ExternalChannelFactoryReflect.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/ExternalChannelFactorySuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/ExternalChannelMock.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/ExternalChannelV2Mock.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala

#516 Fix JDBC source and other sources error handling.

---

pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGenerator.scala
pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGeneratorBase.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/SqlGeneratorDummy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorGenericSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorMicrosoftSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcSparkUtilsSuite.scala

#510 Improve the way schema queries are generated

---

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala

Create sink only once

---

pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveFormat.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveFormatSuite.scala

#561 Fix the absence of iceberg in the HiveFormat enumeration

---

pramen/api/pom.xml
pramen/core/pom.xml
pramen/extras/pom.xml
pramen/pom.xml

#565 Add POM files for better integration with IDEs.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorLoader.scala

#570 Add support for the new Cloudera Hive driver.

---

README.md
pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala
pramen/core/src/test/resources/test/config/integration_ingestion_native.conf
pramen/core/src/test/scala/za/co/absa/pramen/core/integration/JdbcNativeTableLongSuite.scala

#551 Allow specifying special characters per-source.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/sink/SparkSink.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/sink/SparkSinkSuite.scala

#574 Pro-actively initialize JDBC driver of SparkSink when used with JDBC target.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala

#576 Fix setting of autocommit to false is not supported by some JDBC drivers

---

pramen/build.sbt
pramen/project/plugins.sbt

#577 Add auto close and release to Sonatype for CI/CD releases.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/lock/TokenLockHadoopPath.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/lock/TokenLockJdbc.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/lock/TokenLockMongoDb.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JvmUtils.scala

#583 Fix removal of shutdown hooks during shutdown causing cascade failures.

---

pramen/core/src/main/scala/za/co/absa/pramen/core/notify/Sendable.scala

#584 Add timeout for sending emails (5 minutes).

---

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorMicrosoftSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JvmUtilsSuite.scala

#588 Fix SQL query for MS SQL Server when the record count of a table exceeds 2 billion 

---

.github/workflows/scala.yml
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/Metastore.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/MetaTable.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistence.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceNull.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkJob.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
pramen/core/src/main/scala/za/co/absa/pramen/core/utils/FsUtils.scala
pramen/core/src/test/resources/test/config/integration_file_source_sink.conf
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala
pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/sink/PostProcessingSink.scala

#592 Allow sinks depend on other sinks.
