pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJob.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJobSuite.scala
…for a project name agnostic integration.
=> Rename pramen_metastore_tables -> metastore_tables in generated yaml

README.md
- changed dependant table to one referenced in sourcing section
- changed output table for transformer to "transformed_table1" - think this would be more understandable as a modified version of the original table
- changed sink table to align to transformer output table names
=> changed example to align to existing tables

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/JdbcUrlSelector.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/PipelineSparkSessionBuilder.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/source/SparkSource.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGenerator.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDb2.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorGeneric.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ConfigUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/ConfigUtilsSuite.scala
DB2 is now supported as both JDBC Native connection (when an input query is used) or via Spark JDBC source (when an input table is specified).
During the implementation of the feature a bug was fixed - custom JDBC properties didn't propagate when JDBC Native was used. This is fixed.
Closes #52, #53
=> Add support for DB2

README.md, pramen-py/transformations/identity_transformer/__init__.py, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceDelta.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobPreRunStatus.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/RunStatus.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sink/CmdLineSink.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sink/LocalCsvSink.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/transformers/IdentityTransformer.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SinkJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/sink/LocalCsvSinkSuite.scala
Adds a new parameter for specifying the minimum records required for
- Ingestion
- Sending data to a sink
Transformations can now run on date ranges containing 0 records, as long as ingestion and previous steps have succeeded.
=> #68 Add minimum records for ingestion

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ConfigUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/ConfigUtilsSuite.scala
Improved rendering of config trees. Now arrays and objects are flattened and every line of the rendered config corresponds to a primitive value or array of primitive values. 
```
pramen.sources[0].factory.class="za.co.absa.pramen.core.source.SparkSource"
pramen.sources[0].name="csv"
pramen.sources[0].format="csv"
pramen.sources[0].notification.targets=["a"  "b"  "c"]
...
pramen.sources[1].jdbc.password=[ redacted ]
...
```
Because of the flattened keys like `pramen.sources[1].jdbc.password`, the `getRedactedFlatConfig()` method should now work properly on matching the "password" token inside the key and redacting the value. Before, the password was hiding inside `pramen.sources` array as a value and was not redacted.
I was thinking how to do this in a nice way and discovered the …
=> #113 Improved rendering of config arrays and objects in logs.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/sink/LocalCsvSink.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sink/SparkSink.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/sink/SparkSinkSuite.scala
Added a simple Spark sink which performs `df.write(...)` under the hood (with options provided by the configuration of the sink).
Below are the possible config options to specify
```config
{
name = "spark_sink"
factory.class = "za.co.absa.pramen.core.sink.SparkSink"
format = "parquet"
mode = "overwrite"
number.of.partitions = 10
records.per.partition = 1000000
save.empty = true
partition.by = [ pramen_info_date ]
option {
compression = "gzip"
}
}
```
Both `number.of.partitions` and `records.per.partition` can be set but not both at once.  If both are set, the sink raises IllegalArgumentException. However, this poses problem when we define a sink in `pramen.sinks` with `number.of.partitions = 5` and then override the sink setting in some specific table in `pramen.operations` with …
=> #115 Add Spark sink

README.md, pramen/runner/src/main/scala/za/co/absa/pramen/runner/RunnerCommons.scala, pramen/runner/src/main/scala/za/co/absa/pramen/runner/cmd/CmdLineConfig.scala, pramen/runner/src/test/scala/za/co/absa/pramen/tests/CmdLineLineConfigSuite.scala
The reason for the PR is that some environments have WARN as the default root level, possibly to make notebook output  quiet. But Pramen logs are unless at WARN level. So I'e introduced a command line argument that can override the root log level of log4j.
=> #122 allow overriding root log level

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/process/ProcessRunner.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/process/ProcessRunnerImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sink/CmdLineSink.scala, pramen/core/src/test/resources/log4j.properties, pramen/core/src/test/resources/log4j2.properties, pramen/core/src/test/scala/za/co/absa/pramen/core/fixtures/ScriptProcessRunnerFixture.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummyProcessRunner.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/process/ProcessRunnerSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/sink/CmdLineSinkSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/process/ProcessRunnerSuite.scala, pramen/extras/src/test/resources/log4j.properties, pramen/extras/src/test/resources/log4j2.properties
Changes:
- `temp.hadoop.path` and `format` are no longer mandatory. If not specified, the data won't be prepared before running the command. The command will just run at the specified scheduled day.
- Added new non-mandatory options:
- `record.count.regex` - a RegEx expression for extracting the number of records written from the program output.
- `zero.records.success.regex` -  a RegEx expression for extracting a success of the job with zero records written, if it is different from the one defined at `record.count.regex`.
- `failure.regex` - a RegEx expression for extracting a success of the job even if the exit code is 0.
- `output.filter.regex` - a list of RegEx expressions to filter out program's output so logs won't be too big. It can be used to filter out progress lines from the …
=> #132 make command line sink more generic

pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JsonUtilsSuite.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/fixtures/TempDirFixture.scala, pramen/runner/src/test/scala/za/co/absa/pramen/tests/CmdLineLineConfigSuite.scala
In the end, this was a very simple fix (just closing a file in `TempDirFixture`). Although there are some complexities in tests which compare two strings (I will describe them in comments).
=> #146 Fix failing tests from extras module on Windows.

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/PipelineSparkSessionBuilder.scala
Aliaksei noticed that Pramen still registered as "Syncwatcher - <Pipeline name>", simple change to update to Pramen
=> Updated Spark Application Name (Syncwatcher -> Pramen)

pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/TaskCompleted.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/RunStatus.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JvmUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/journal/JournalMock.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TaskRunReasonSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/TaskCompletedSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/jobrunner/TaskRunnerMultithreadedSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/task/RunStatusSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/task/TaskRunnerBaseSuite.scala
- The journal table has quite a legacy format for compatibility with SyncWatcher. Maybe the journal can be deprecated in the future, or made optional
- Extended RunStatus with additional methods since these reasons are pattern matched and rendered for different reasons. New methods unify the way these status messages are rendered.
- Tested end to end
=> #153 Fix pipeline does not publish task completion events to the journal table.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/RuntimeConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationDef.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/OperationDefFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/OperationDefSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/jobrunner/TaskRunnerMultithreadedSuite.scala
Add an option to specify how many "threads" should a certain task consume with regards to the total number of threads set by `pramen.parallel.tasks`. 
An example:
```
pramen {
pipeline.name = "A testing pipeline"
parallel.tasks = 4
}
pramen.operations = [
{
name = "easy job"
...
consume.threads = 1 # not a resource intensive job, so Pramen can run 4 of these at one time (if nothing else is running of course)
},
{
name = "hard job"
...
consume.threads = 4 # run only one instance of this operation at a time
},
]
```
These are not real threads, it is more akin to an indication to pramen saying: "This is a resource-intenstive operation, so you don't want to have many of these running at once".  
I tried thinking of a better name to not be as confusing but did not come up with anything useful. …
=> #151 Specify number of threads to consume by a task.

README.md, pramen/examples/enceladus_single_config/daily_ingestion.conf, pramen/examples/enceladus_single_config/weekly_ingestion.conf, pramen/examples/enceladus_sourcing/daily_ingestion.conf, pramen/examples/enceladus_sourcing/daily_snapshot.conf, pramen/extras/src/main/scala/za/co/absa/pramen/extras/query/QueryExecutor.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/query/QueryExecutorSpark.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusConfig.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusUtils.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/InfoVersionStatus.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/utils/FsUtils.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/mocks/QueryExecutorSpy.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusConfigSuite.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusSinkSuite.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusUtilsSuite.scala, pramen/project/Dependencies.scala, pramen/project/plugins.sbt, pramen/version.sbt
- The autodetection is used when `output.info.version = auto` or not specified
- Either `output.publish.base.path` or `output.hive.table` should be specified
- The publish base path should exist if specified
- If no partitions found the version number will be 1
- Otherwise, `maximum info version published + 1`
=> #149 Autodetect Enceladus info version

pramen/runner/src/test/resources/log4j.properties, pramen/runner/src/test/resources/log4j2.properties, pramen/runner/src/test/scala/za/co/absa/pramen/base/ExitException.scala, pramen/runner/src/test/scala/za/co/absa/pramen/base/NoExitSecurityManager.scala, pramen/runner/src/test/scala/za/co/absa/pramen/runner/CmdLineConfigSuite.scala, pramen/runner/src/test/scala/za/co/absa/pramen/runner/PipelineRunnerSuite.scala, pramen/runner/src/test/scala/za/co/absa/pramen/runner/RunnerCommonsSuite.scala
I thought that methods that contain `System.exit()` can't be tested. But after reading about JVM internals, started searching and found how a `SecurityManager` manager could be used to prevent `System.exit()` from exiting the test app,
=> Add a test suite that checks the runner exit code.

.github/workflows/scala.yml, pramen/project/Versions.scala, pramen/project/plugins.sbt, pramen/version.sbt
https://github.com/AbsaOSS/pramen/releases/tag/v1.2.2
* #132 Make command line sink more generic by @yruslan in https://github.com/AbsaOSS/pramen/pull/142
* #146 Fix failing tests from extras module on Windows. by @jirifilip in https://github.com/AbsaOSS/pramen/pull/147
* #145 Add an option for failing the pipeline if no data is available at the source by @yruslan in https://github.com/AbsaOSS/pramen/pull/148
* #150 Updated Spark Application Name (Syncwatcher -> Pramen) by @dwfchu in https://github.com/AbsaOSS/pramen/pull/150
* #153 Fix pipeline does not publish task completion events to the journal table. by @yruslan in https://github.com/AbsaOSS/pramen/pull/154
* #151 Specify number of threads to consume by a task. by @jirifilip in https://github.com/AbsaOSS/pramen/pull/156
* #149 …
=> Release Pramen v.1.2.2

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/FsUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/FsUtilsSuite.scala
Affects only bookeeper backed by HDFS storage.
=> #178 Add the workaround for the file appending issue.

pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/PipelineSparkSessionBuilder.scala, pramen/core/src/test/resources/reference.conf
This is so that Pramen jobs can use cluster defaults for Hive configuration. The old logic didn't enable Hive support if no Hive-related options were configured.
=> #196 Make Hive enablement an explicit parameter.

.github/workflows/jacoco.yml, .github/workflows/scala.yml, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SinkJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransferJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/QueryExecutorSparkSuite.scala, pramen/project/Versions.scala, pramen/project/plugins.sbt
Update Jacoco to the internal version that generates per-file report for pull request.
The current level of project test coverage is 75%. We can adjust it later when we know which direction it is going to go.
=> Add unit test coverage for Scala via Jacoco.

.github/workflows/jacoco.yml, README.md, pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveApi.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/HiveDefaultConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveFormat.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelper.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelperSparkCatalog.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelperSql.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/HiveConfigSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/HiveDefaultConfigSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveApiSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSparkCatalogSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSqlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSuite.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/StandardizationSink.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/StandardizationSinkSuite.scala
This adds another HiveHelper implementation that is based on Spark Catalog, rather than running explicit SQL query against Hive metastore.
Spark Catalog allows natural management of Glue Catalog tables in Delta format, provided that prerequisites for the Glue job are met: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-delta-lake.html.
Global Hive implementation selection:
```hocon
pramen {
hive.api = "sql"
}
```
Per-metastore table Hive implementation selection:
```hocon
pramen.metastore {
tables = [
{
hive.api = "spark_catalog"
hive.table = "table"
}
]
}
```
Standardization Sink Hive implementation selection:
```hocon
pramen.sinks = [
{
name = "mysink"
factory.class = "za.co.absa.pramen.extras.sink.StandardizationSink"
hive = {
api = "sql"
}
}
]
```
=> #203 Add spark catalog support

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala
We hit some issues on Databricks where, if we run a Pramen job repeatedly on an all-purpose cluster or in a notebook, the `AppContext` gets created only once. In the `AppContext` creation process, metastore config is parsed and configured. Thus, if we change the metastore config between runs on an all-purpose cluster, it has no effect on the pipeline run, since Pramen will be using an already created `AppContext` from the JVM process (with old metastore table definitions).
So far did not remove any dead code (`AppContextFactory` and its tests) in case we would like to use it in the future.
=> Make AppRunner recreate AppContext on every run

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JvmUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JvmUtilsSuite.scala, pramen/examples/enceladus_single_config/daily_ingestion.conf, pramen/extras/src/main/scala/za/co/absa/pramen/extras/sink/EnceladusSink.scala, pramen/extras/src/main/scala/za/co/absa/pramen/extras/utils/FsUtils.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/tests/sink/EnceladusSinkSuite.scala
These features were in the separate branch for a while. But now I think they can be merged. 
The new features are very Enceladus-specific.
- Autodelete standardization and publish partitions on re-runs to simplify operation of ingestion pipelines.
- Allow Hive table creation at the end of Enceladus job (it was only repairing existing tables before)
- Fix JDBC password leakage in certain circumstances
P.S.
I'm going to fix the next coverage in some other PRs.
Closes #207
=> EnceladusSink - several new features

pramen/core/src/main/scala/za/co/absa/pramen/core/ExternalChannelFactoryReflect.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/MetaTable.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PipelineDef.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ConfigUtils.scala, pramen/core/src/test/resources/test/config/pipeline_v3.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/MetastoreSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PipelineDefSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/ConfigUtilsSuite.scala
I was trying several attempts and didn't like all of them.
1. Reading configs separately as a TypeSafe `Config` and them combining them into a single `Config` object didn't work since it is not possible to add an array of objects to a config in runtime.
2. Making multiple-configs-aware Sources/Sinks/Operations deserializer complicates Pramen code a lot, and requires enormous change across the project.
So I came with a compromise solution. See #205
=> #205 Allows spreading object array elements among multiple config files.

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelperSql.scala
This fixes an issue of Hive table creation that we encountered in AWS. This affects only 'transfer' jobs that sends data from source directly to a sink (without the metastore).
Will release a new version of Pramen after this is merged.
=> Hotfix: make sure fields that have empty names are not part of Hive DDL.

pramen/version.sbt
The released version contains the following hotfix:
#213 Hotfix: make sure fields that have empty names are not part of Hive DDL
=> Release hotfix with the version 1.4.3

pramen-py/.env.local, pramen-py/src/pramen_py/metastore/reader.py, pramen-py/src/pramen_py/metastore/writer.py, pramen-py/tests/conftest.py, pramen-py/tests/test_metastore/test_reader/test_get_latest_available_date.py, pramen-py/tests/test_metastore/test_reader/test_get_table.py, pramen-py/tests/test_metastore/test_writer/test_writer.py
Closes #166 
- Fix `get_latest_available_date` for delta format so that it returns `datetime.date` type instead of string (same as parquet behaviour) 
- renamed `get_data_stub` fixture to `test_dataframe` for better readability
This is a really simple fix but I think better approach would be to extract behaviour for manipulating/persisting delta and parquet formats from `MetastoreReader` because right now, we have branches for delta/parquet in almost every metastore reader method. I plan to tackle this when fixing #165 (we need some layer of abstraction for paths/tables and parquets/deltas)
=> #166 - Fix get_latest_available_date for delta format

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ClassLoaderUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummyEmptySingletonClass.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummySingletonClass.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummySingletonFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummySingletonTrait.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/DummyTransformer1.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/DummyTransformer2.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/DummyTransformer3.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/OperationSplitterSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/ClassLoaderUtilsSuite.scala
…instead of the full app configuration.
=> #229 Allow passing transformer configuration to the constructor 

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransformExpression.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/test/resources/log4j.properties, pramen/core/src/test/resources/log4j2.properties, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/OperationDefSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PipelineDefSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SinkJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SinkTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SourceTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransferJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransferTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/task/TaskRunnerBaseSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala
Adds the capability:
```hocon
transformations = [
{ col = "col1", comment = "A comment for existing col1" }
{ col = "col2", expr = "lower(col1)", comment = "A comment for new col2" }
],
```
=> #239 Add support for column comments in inilne transformations.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/PipelineSparkSessionBuilder.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/PipelineSparkSessionBuilderSuite.scala
```hocon
pramen.spark.app.name = "My app - "${pramen.pipeline.name}" on "${praman.environment.name}
```
=> #258 Make Spark Application name configurable.

.github/workflows/scala.yml, pramen/build.sbt, pramen/project/Versions.scala, pramen/project/build.properties
=> #270 Add Spark 3.5.0 support, update Scala and Spark dependencies to the latest patches.

README.md, pramen/api/src/main/scala/za/co/absa/pramen/api/Pramen.scala, pramen/api/src/test/scala/za/co/absa/pramen/api/mocks/DummyPramen.scala, pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/PramenImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/app/AppConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/app/AppContextImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/HookConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/test/resources/test/config/pipeline_v2_empty.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/PramenHookSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/PramenImplSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/HookConfigSuite.scala
=> Add ability to specify custom startup and shutdown hooks.

pramen/api/src/main/scala/za/co/absa/pramen/api/NotificationBuilder.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/HookConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotification.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilder.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationDirector.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/NotificationBuilderImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/test/resources/test/notify/test_pipeline_email_body_complex.txt, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineNotificationFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TaskResultFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TestPrototypes.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/PipelineNotificationBuilderSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/state/NotificationBuilderImplSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala
=> Implement custom notification signatures for email notifications.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/model/BookkeepingRecords.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/model/MetadataRecords.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/model/SchemaRecords.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/journal/model/JournalTasks.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/impl/JdbcFieldMetadata.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/fixtures/RelationalDbFixture.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/samples/RdbExampleTable.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcNativeUtilsSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcSparkUtilsSuite.scala, pramen/examples/enceladus_sourcing/sources.conf, pramen/examples/jdbc_sourcing/sources.conf
Closes #276
Example: for
```
NAME VARCHAR(50)
DESCRIPTION VARCHAR
```
Thye schema when loaded using the JDBC source with `enable.schema.metadata = true`
```json
{
"type" : "struct",
"fields" : [ {
"name" : "NAME",
"type" : "string",
"nullable" : true,
"metadata" : {
"maxLength" : 50
}
}, {
"name" : "DESCRIPTION",
"type" : "string",
"nullable" : true,
"metadata" : { }
} ]
}
```
=> Add maximumLength field metadata for JDBC 'varchar' fields

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransformationJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/jobrunner/ConcurrentJobRunnerImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/Emoji.scala
=> #284 Fix lock/semaphore/channel resource release on fatal errors.

README.md, pramen/version.sbt
* #284 Fix lock/semaphore/channel resource release on fatal errors in https://github.com/AbsaOSS/pramen/pull/285
* #287 Fix sending of email notifications if instantiating of hooks failed in https://github.com/AbsaOSS/pramen/pull/289
=> Release v1.6.5

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/splitter/ScheduleStrategySourcing.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/splitter/ScheduleStrategyTransformation.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/splitter/ScheduleStrategyUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/splitter/ScheduleStrategySuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/splitter/ScheduleStrategyUtilsSuite.scala
Closes #292
The bug made partitions that are already loaded consider late data in certain circumstances.
=> #292 Fix the last expected info date calculation.

README.md, pramen/build.sbt, pramen/core/src/main/scala/za/co/absa/pramen/core/RunnerCommons.scala, pramen/project/Dependencies.scala, pramen/project/Versions.scala
Closes #298
Delta format is now not included in the pramen runner bundle by default, so you don't need to specify Spark version and just run
```sh
sbt ++2.12.18 assembly
```
=> #298 Do not include Delta Lake classes in the runner bundle by default.

README.md, pramen/build.sbt, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/OrchestratorImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/CsvUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/samples/RdbExampleTable.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcNativeUtilsSuite.scala
=> #283 Add support for using Spark JDBC connectors for SELECT SQL queries.

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/jobrunner/ConcurrentJobRunnerImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/orchestrator/OrchestratorImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/test/resources/test/config/integration_parallel_execution.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/MultiJobTransformersLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/ParallelExecutionLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/FailingTransformer.scala
This might not fix all the causes of #302, but should prevent most of it from happening.
=> #302 Improve handling of fatal errors in parallel pipeline executions.

pramen/project/Versions.scala
This is because channels have is a bug in `foreach()` which is fixed in 0.1.5.
https://github.com/yruslan/channel_scala/commit/d4ed07481473d0ff0558ed30e7a820b355f3eff3
=> Update the version of channels to 0.1.5

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala
=> #312 Fix the requirement of 'information.date.format.sql' to be present for the JDBC source.

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGenerator.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDb2.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDenodo.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorGeneric.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHive.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHsqlDb.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorOracle.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorPostgreSQL.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorSas.scala, pramen/core/src/test/resources/test/config/integration_inner_source.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/InnerSourceLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/transformer/InnerSourceTransformer.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala
=> #317 Escape column names in SQL queries when it contains non-alphanumeric characters or a possible keyword.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/QuotingPolicy.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGenerator.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDb2.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDenodo.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorGeneric.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHive.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHsqlDb.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorOracle.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorPostgreSQL.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorSas.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/DummySqlConfigFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/QuotingPolicySuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcSparkUtilsSuite.scala
Closes #325
The PR removes the check of input table name of column name against the list of keywords because it cannot be exhausting, but adds the user the option to control how thorough the quoting policy will be. If quoting is enables ('auto' or 'always') validation of identifiers are mandatory.
The new option:
```hocon
identifier.quoting.policy = "auto"
```
=> #325 Add quoting policy that help validate and quote identifiers that are passed to SQL queries.

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala
Closes #324
The expression is chosen such so it is supported by all MS SQL Server flavors.
This is only applicable if the info date column is a varchar(). If the input column is datetime, the current CONVERT() works just fine.
Tested end to end.
=> #324 Make string to date conversion for MS SQL Server queries graceful.

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorSuite.scala
...rather than rely on non-deterministic ISDATE().
List o formats: https://www.mssqltips.com/sqlservertip/1145/date-and-time-conversions-using-sql-server/
Tested end to end.
Related to #324
=> Use safer 'TRY_CONVERT' with the explicit format reference number for MS SQL Server.

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/OperationSplitter.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/OperationSplitterSuite.scala
=> #369 Fix lazy created lazy if they depend on transient tables.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/JdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/impl/ResultSetToRowIterator.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcNativeUtilsSuite.scala
Closes #375 
This PR makes Pamen built-in JDBC reader sanitize timestamps, having them in year ranges 1...9999.
This automatically solves PostgreSQL infinity timestamp issue, and possible other issues without sacrificing features much.
This is how the PostgreSql table with infinities looks like (displayed in GMT+2 time zone):
=> #375 Add workaround for timestamp overflows.

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala, pramen/core/src/test/resources/test/config/integration_ingestion_native.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/JdbcNativeTableLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/source/JdbcSourceSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala
Closes #376 
This PR allow usage of `input.table="db_tatble"` together with `use.jdbc.native=true`.
In order to avoid code dublication, some pieces of code from `TableReaderJdbc` and `TableReaderJdbcNative` is extracted into a common base abstract class `TableReaderJdbcBase`.
=> #376 Add support for 'input.table' when JDBC Native is used with supported SQL dialects.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorLoader.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMySQL.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala
Closes #378 
Tested on an actual MySQL endpoint, with and without info date column, and with various info date column types.
=> #378 Add support for MySQL databases in the JDBC source.

.github/workflows/release.yml, .github/workflows/scala.yml, pramen/build.sbt, pramen/examples/combined_example.sh, pramen/project/Dependencies.scala, pramen/project/Versions.scala, pramen/project/build.properties
Closes #382
Updates versions to latest patches, and replaces obsolete `setup-scala` plugin so that JDK is latest, not old like this:
With the change:
=> Update versions of Scala, Spark and sbt for builds and CI/CD.

pramen/core/src/main/scala/za/co/absa/pramen/core/exceptions/OsSignalException.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/exceptions/ThreadStackTrace.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/message/MessageBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/runner/PipelineRunner.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/state/PipelineStateSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala
Closes #388 
If the pipeline is interrupted with Ctrl+C, or kill (SIGTERM), or connection to the terminal is lost (SIGHUP), Pramen will now specify the exact signal received, and include stack traces of all [non-daemon] threads in the email notification.
This is useful when the pipeline is killed due to some kind of deadlock to debug the place where the deadlock happened.
=> #388 Handle OS signals and include thread stack traces in email notifications

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/JdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcNativeUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/impl/ResultSetToRowIterator.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcNativeUtilsSuite.scala
=> #387 Implement handling DATE overflows that can happen with PotgreSQL infinity date values.

README.md, pramen/api/src/main/scala/za/co/absa/pramen/api/FieldChange.scala, pramen/api/src/main/scala/za/co/absa/pramen/api/PipelineNotificationTarget.scala, pramen/api/src/main/scala/za/co/absa/pramen/api/SchemaDifference.scala, pramen/api/src/main/scala/za/co/absa/pramen/api/TaskNotification.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/PipelineNotificationTargetFactory.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotification.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilder.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/PipelineNotificationFailure.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskResult.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/test/resources/test/config/integration_notification_targets.conf, pramen/core/src/test/scala/za/co/absa/pramen/core/TaskNotificationFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/NotificationTargetSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/integration/ParallelExecutionLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/FieldChangeFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/PipelineNotificationFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/SchemaDifferenceFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/TaskResultFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/NotificationTargetMock.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/PipelineNotificationBuilderSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/PipelineNotificationTargetMock.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala
=> #372 Add global notification targets

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala
=> #399 Add ability to use date expressions and formatting in jdbc native sql expressions

pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PramenSignalHandler.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/state/PramenSignalHandlerSuite.scala
=> #407 Signal handling always stopping the pipeline, forward the signal to the original handler instead

pramen/core/src/test/scala/za/co/absa/pramen/core/fixtures/MongoDbFixture.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/dao/MongoDbSingleton.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperMongoDbLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/JournalMongoDbSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/lock/TokenLockMongoDbSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/BuildPropertyUtilsSuite.scala
This PR adds the skipping of MongoDB tests on platforms that don't support embedded MongoDB. 
I decided to use this simple approach because:
- Tests for MongoDB are not ignored on GitHub runners, so errors luckily should be caught in CI/CD.
- MongoDB is being phased out in favor of PostgreSQL database for bookeeping, I'm not sure if anybody is using it now.
- I hope when MongoDB is used again bookkeeping for some reason, we can switch to a newer version of embedded MongoDB to support more platforms.
- I've tried upgrading the embedded MongoDB library, and it is not trivial, many interfaces have changed, so I went for the simple solution for now.
The issue will remain open so that a better solution is implemented eventually.
=> #435 Fix running tests involving embedded MongoDb on incompatible platforms.

pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationDirector.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationDirectorSuite.scala
This resulted in pipeline custom notification failures were not part of notification emails.
Closes #426
=> #426 Fix addPipelineNotificationFailure() not being called.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/JdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/QueryExecutorJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/QueryExecutorSpark.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/QueryExecutorJdbcSuite.scala
Closes #438
Added option:
```hocon
hive {
#...
optimize.exist.query = true
}
```
to any Hive context. If 
- `false` (default = previous behavior), uses this query for checking Hive table existence:
`SELECT 1 FROM my_db.my_table WHERE 0 = 1  `
- `true`, uses this query for checking Hive table existence:
`DESCRIBE my_db.my_table`
(this is faster since it never touhces data, but may depend on Hive dialect)
In addition, added more logging related to Hive table existence check for easier debugging Hive issues.
=> #438 Optimize hive table existence query

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/AppRunnerSuite.scala
=> #446 Make all dependencies passive when running pipelines for date ranges

pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala
...so that schema changes that happen within a day are detected.
Closes #456
=> #456 Fix schema changes detection logic.

README.md, pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/IngestionJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/Job.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransferJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransformationJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/job/JobBaseDummy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/job/JobSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/JobBaseSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/SinkJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransferJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/TransformationJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/task/TaskRunnerBaseSuite.scala
=> #469 Add options to fail on late and new data separately

pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/message/MessageBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/message/MessageBuilderHtmlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala
=> #476 Allow configuring maximum length of error messages in email notifications

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/BookkeeperConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/HadoopFormat.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/Bookkeeper.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/BookkeeperDeltaBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/BookkeeperDeltaPath.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/BookkeeperDeltaTable.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/bookkeeper/BookkeeperText.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/journal/JournalHadoopCsv.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/journal/JournalHadoopDeltaPath.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/journal/JournalHadoopDeltaTable.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/lock/TokenLockFactoryHadoopPath.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/lock/TokenLockHadoopPath.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/BookkeepingConfigFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/BookkeeperConfigSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperCommonSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperDeltaPathLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperDeltaTableLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/bookkeeper/BookkeeperSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/JournalHadoopCsvSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/JournalHadoopDeltaPathLongSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/JournalHadoopDeltaPathSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/journal/JournalHadoopDeltaTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/lock/TokenLockHadoopPathSuite.scala
Closes #475 
This requires Delta Lake format support from the cluster you are running pipelines at.
You can use wither a path:
```hocon
pramen.bookkeeping {
enabled = "true"
hadoop.format = "delta"
location = "s3://path"
}
```
or a set of managed tables:
```hocon
pramen.bookkeeping {
enabled = "true"
hadoop.format = "delta"
delta.database = "my_db"  # Optional. 'default' will be used if not speified
delta.table.prefix = "bk_"
}
```
=> #475 Add Delta Lake location or managed table as a bookkeeping storage option

pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGenerator.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDb2.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDenodo.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorGeneric.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHive.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorHsqlDb.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMySQL.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorOracle.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorPostgreSQL.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorSas.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/SqlGeneratorDummy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala
=> #483 Fix count() queries with MS SQL and other SQL dialects.

pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGenerator.scala, pramen/api/src/main/scala/za/co/absa/pramen/api/sql/SqlGeneratorBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorMicrosoft.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/SqlGeneratorDummy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala
=> #482 Fix reading of column description for tables that are specified in quotes

.github/workflows/release.yml, pramen/core/src/main/scala/za/co/absa/pramen/core/expr/DateExprEvaluator.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/expr/parser/Parser.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/expr/DateExprEvaluatorSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/StringUtilsSuite.scala
=> #489 Fix date expressions calculation for JDBC with SQL queries.

.github/workflows/scala.yml, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/splitter/ScheduleStrategyUtils.scala
=> #496 Fix handling of retrospectively updated jobs.

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/impl/ResultSetToRowIterator.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/IngestionJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/samples/RdbExampleTable.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorLoaderSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/JdbcNativeUtilsSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala
Closes #501
The fix is tested and confirmed working.
=> #501 Fix Jdbc Native treating of nullable fields.

README.md, pramen/core/src/main/scala/za/co/absa/pramen/core/app/config/RuntimeConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/jobrunner/ConcurrentJobRunnerImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/task/TaskRunnerMultithreaded.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/RuntimeConfigFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/app/config/RuntimeConfigSuite.scala
=> #498 Allow dynamically setting job descriptions

pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/JobBase.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/SinkJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/TransformationJob.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala
=> #508 Fix the way descriptions are fetched for JDBC tables.

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JdbcSparkUtils.scala
* Fix Spark Application Description not always being set in https://github.com/AbsaOSS/pramen/pull/506
* #508 Fix the way descriptions are fetched for JDBC tables in https://github.com/AbsaOSS/pramen/pull/509
* Fix jobs being re-run are marked as started because of an obsolete dependency in email notifications in https://github.com/AbsaOSS/pramen/pull/509
=> Merge support/1.9 for the v1.9.11

pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbc.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/TableReaderJdbcNative.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/reader/model/TableReaderJdbcConfig.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/source/JdbcSource.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcNativeSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/reader/TableReaderJdbcSuite.scala
=> #398 Fix the usage of custom schema and decimal corrections with Hive JDBC source.

README.md, pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/config/Keys.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/Sendable.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilder.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationDirector.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationEmail.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/ValidatedEmails.scala, pramen/core/src/test/resources/log4j.properties, pramen/core/src/test/resources/log4j2.properties, pramen/core/src/test/resources/test/notify/test_pipeline_email_body_complex.txt, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/notify/PipelineNotificationBuilderSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/PipelineNotificationEmailSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationDirectorSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/runner/splitter/ScheduleStrategyIncrementalSuite.scala
=> #531 Add the ability to restrict domains of emails that can be used as email recipients

pramen/core/src/main/resources/reference.conf, pramen/core/src/main/scala/za/co/absa/pramen/core/notify/pipeline/PipelineNotificationBuilderHtml.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/notify/pipeline/PipelineNotificationBuilderHtmlSuite.scala
=> #488 Make Pramen more strict on successes and failures of pipelines.

pramen/api/src/main/scala/za/co/absa/pramen/api/DataFormat.scala, pramen/api/src/main/scala/za/co/absa/pramen/api/PartitionInfo.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/MetastoreImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/model/DataFormatParser.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistence.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceDelta.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/metastore/peristence/MetastorePersistenceParquet.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJob.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/DataFormatSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/HiveConfigSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/model/MetaTableSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceParquetSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/metastore/persistence/MetastorePersistenceSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/MetaTableFactory.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/job/JobSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/metastore/MetastoreSpy.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/mocks/sink/CmdLineSinkSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/pipeline/PythonTransformationJobSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/source/SourceValidationSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/transformers/ConversionTransformerSuite.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/notification/EcsNotificationTargetSuite.scala, pramen/extras/src/test/scala/za/co/absa/pramen/extras/notification/EcsPipelineNotificationTargetSuite.scala
=> #534 Allow specifying the explicit number of partitions for metastore tables

pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorDatabricks.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/SqlGeneratorLoader.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/sql/dialects/DatabricksDialect.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/sql/SqlGeneratorDatabricksSuite.scala
=> #542 Add databricks driver processing in SqlGeneratorLoader and provide databricks dialect using

pramen/core/src/main/scala/za/co/absa/pramen/core/utils/SparkUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/hive/HiveHelperSql.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/SparkUtilsSuite.scala, pramen/core/src/test/scala/za/co/absa/pramen/core/tests/utils/hive/HiveHelperSqlSuite.scala
=> #552 Fix Hive DDL for tables with long descriptions with '\n' characters.

pramen/build.sbt, pramen/core/src/main/scala/za/co/absa/pramen/core/runner/AppRunner.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PipelineStateImpl.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/PramenSignalHandler.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/state/SystemExitCatcherSecurityManager.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/JvmUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/StringUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/ThreadUtils.scala, pramen/core/src/main/scala/za/co/absa/pramen/core/utils/impl/SystemExitCatcherSecurityManager.scala, pramen/project/plugins.sbt
Closes #585 
For example, here how [truncated] stack traces look like when I added `System.exit(0)` to the Identity transformer `run()` method:
```
The application was interrupted by a signal: System.exit().
Stack trace of threads at the moment of the interruption:
Thread 0 (pool-32-thread-4): 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
Thread 6 (pool-35-thread-1): 
java.lang.Thread.dumpThreads(Native Method)
java.lang.Thread.getAllStackTraces(Thread.java:1615)
za.co.absa.pramen.core.utils.JvmUtils$.getStackTraces(JvmUtils.scala:51)
za.co.absa.pramen.core.utils.impl.SystemExitCatcherSecurityManager.checkExit(SystemExitCatcherSecurityManager.scala:31)
java.lang.Runtime.exit(Runtime.java:101)
> …
```
=> #585 Add stack traces to notifications when the code invokes `System.exit()`
